'use strict';
const app=document.querySelector('#app');
let cards=[],state=null,ART={assets:{},superstars:{}};
const VERSION='v0.9.8',MAX_HP=40,HAND_SIZE=5,MAX_MOM=99,STORE='wa-mobile-v098';
const MOM_TYPES=['Agility','Knowledge','Strength','Strike','Technical','Attitude'];
const SUPERSTARS={austin:{key:'austin',name:'STONE COLD',ability:'Bionic Redneck',entrance:'Glass Shatters',hp:40,style:'brawler'},rock:{key:'rock',name:'THE ROCK',ability:"People’s Champion",entrance:'If You Smell',hp:40,style:'balanced'},tripleh:{key:'tripleh',name:'TRIPLE H',ability:'Cerebral Assassin',entrance:'King of Kings',hp:42,style:'technical'},angle:{key:'angle',name:'KURT ANGLE',ability:'Olympic Hero',entrance:'Medal Ceremony',hp:38,style:'submission'},jericho:{key:'jericho',name:'CHRIS JERICHO',ability:'Ayatollah of Rock ‘n’ Rolla',entrance:'Break the Walls Down',hp:37,style:'agile'},undertaker:{key:'undertaker',name:'THE UNDERTAKER',ability:'Deadman Rising',entrance:'Funeral Bell',hp:44,style:'power'},kane:{key:'kane',name:'KANE',ability:'Big Red Machine',entrance:'Pyro Eruption',hp:44,style:'power'},bigshow:{key:'bigshow',name:'BIG SHOW',ability:'World’s Largest Athlete',entrance:'Giant Entrance',hp:46,style:'power'},spike:{key:'spike',name:'SPIKE DUDLEY',ability:'150 Pounds of Toughness',entrance:'Dudley Charge',hp:34,style:'agile'},hogan:{key:'hogan',name:'HOLLYWOOD HULK HOGAN',ability:'24 Inch Pythons',entrance:'Voodoo Child',hp:43,style:'brawler'}};
let profile=loadProfile(),selectedSuperstar='austin',selectedOpponent='rock',opening=[],matchPlayer='austin';
function loadProfile(){try{const current=JSON.parse(localStorage.getItem(STORE));const prior=JSON.parse(localStorage.getItem('wa-mobile-v080'));const p=current||prior||{};return Object.assign({decks:{},wins:0,losses:0,stats:{},credits:0,xp:0,matchHistory:[],missions:{},firstLaunch:true,settings:{sound:true,animations:true,confirmReset:true}},p)}catch{return{decks:{},wins:0,losses:0,stats:{},credits:0,xp:0,matchHistory:[],missions:{},firstLaunch:true,settings:{sound:true,animations:true,confirmReset:true}}}}
function saveProfile(){localStorage.setItem(STORE,JSON.stringify(profile))}
Promise.all([fetch('data/demo-cards.json').then(r=>{if(!r.ok)throw new Error('Card data failed to load');return r.json()}),fetch('data/artwork-manifest.json').then(r=>r.json())]).then(([x,a])=>{ART=a;cards=x.map(enrichCard);home()}).catch(err=>app.innerHTML=`<section class="screen"><div class="logo">LOAD ERROR</div><p>${esc(err.message)}</p></section>`);

function enrichCard(c){
  const t=(c.description||'').toLowerCase(),mods=(c.modifiers||'').toLowerCase();
  const counterMap={'mad rush':'Mad Rush','in close':'In Close','arm extended':'Arm Extended','leg extended':'Leg Extended','back to foe':'Back To Foe','victim below':'Victim Below','head down':'Head Down','grounded':'Grounded'};
  const inferred=[...(c.counters||[])];
  Object.entries(counterMap).forEach(([needle,pos])=>{if(t.includes(`counters ${needle}`)||t.includes(`counter ${needle}`))inferred.push(pos)});
  const draw=(t.match(/draw (?:one |a |1 |two |2 )?page/g)||[]).reduce((n,x)=>n+(x.includes('two')||x.includes('2 ')?2:1),0);
  let requirement=null;['knowledge','agility','strike','strength','technical'].forEach(x=>{if(t.includes(`if you have any ${x}`)||t.includes(`if you have ${x}`)||t.includes(`only if you have ${x}`))requirement=x[0].toUpperCase()+x.slice(1)});
  const minTurnMatch=t.match(/(?:only )?after turn (\d+)/); const minTurn=minTurnMatch?Number(minTurnMatch[1])+1:(c.minTurn||null);
  const momentumRequirements={}; MOM_TYPES.forEach(type=>{const m=t.match(new RegExp('(?:have|requires?)\\s+(\\d+)\\s+'+type.toLowerCase()));if(m)momentumRequirements[type]=Number(m[1])});
  const discardSelf=(t.match(/discard (?:any |up to )?(one|1|two|2|three|3) page(?:s)? from your hand/)||[])[1];
  const discardOpponent=/opponent discards? (?:a|one|1) (?:random )?page/.test(t)?1:0;
  const recover=/recover (?:a|one|1) page/.test(t)?1:0;
  const preventDamage=/does no damage|prevent all damage/.test(t);
  return {...c,counters:[...new Set(inferred)],counterOnly:c.counterOnly||t.includes('play only as a counter')||t.includes('only be played as a counter'),face:mods.includes('face')||t.includes('(face page'),heel:mods.includes('heel')||t.includes('(heel page'),drawEffect:draw,requirement,hold:mods.includes('hold')||t.includes('each turn')&&t.includes('hold'),releaseChance:(t.match(/(\d+)% chance that this hold is released/)||[])[1]/100||null,conditionalStun:t.includes('if your opponent is not stunned')&&t.includes('stunned'),damageBonus:t.includes('up to +2 damage')?2:0,minTurn,momentumRequirements,discardSelf:discardSelf?(discardSelf==='two'||discardSelf==='2'?2:discardSelf==='three'||discardSelf==='3'?3:1):0,discardOpponent,recoverEffect:recover,preventDamage,uncounterable:c.uncounterable||t.includes("can't be countered")||t.includes('cannot be countered')};
}

const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const artKey=v=>String(v||'').replace(/\.[^.]+$/,'').toLowerCase().replace(/[^a-z0-9]+/g,'');
function cardArt(c){const keys=[c.sourceFile,c.id,c.name];for(const k of keys){const hit=ART.assets?.[artKey(k)];if(hit)return hit.file}return ''}
function starArt(key){return ART.superstars?.[key]?.file||''}
function artImg(src,cls='cardArt',alt=''){return src?`<img class="${cls}" src="${esc(src)}" alt="${esc(alt)}" loading="lazy">`:''}

function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function poolFor(key){return cards.filter(c=>!c.owner||c.owner===key).filter(c=>c.cardClass!=='Entrance')}
function defaultDeckIds(key){const pool=poolFor(key),owned=pool.filter(c=>c.owner===key),general=pool.filter(c=>!c.owner&&c.cardClass!=='Momentum');let ids=[];const momentum=cards.filter(c=>c.cardClass==='Momentum'&&['Agility','Knowledge','Strength','Strike','Technical'].includes(c.momentumType));for(let n=0;n<2;n++)momentum.forEach(c=>ids.push(c.id));owned.forEach(c=>ids.push(c.id));for(let n=0;n<3;n++)general.forEach(c=>{if(c.cardClass!=='Trademark'||!ids.includes(c.id))ids.push(c.id)});return ids.slice(0,55)}
function deckIds(key){return profile.decks[key]?.length?profile.decks[key]:defaultDeckIds(key)}
function buildDeck(key,chosenOpening=[]){const ids=deckIds(key),pool=poolFor(key),made=ids.map((id,i)=>{const c=pool.find(x=>x.id===id);return c?{...c,instance:`${key}-${i}-${Math.random()}`}:null}).filter(Boolean);const first=[];chosenOpening.forEach(id=>{const i=made.findIndex(c=>c.id===id);if(i>=0)first.push(made.splice(i,1)[0])});return [...first,...shuffle(made)]}
function recordFor(key){return profile.stats?.[key]||{wins:0,losses:0,matches:0}}
function home(){state=null;const r=recordFor(selectedSuperstar);app.innerHTML=`<section class="screen home"><div class="logo">WITH AUTHORITY!</div><div class="sub">Private mobile preservation prototype · ${VERSION}<br>${profile.wins||0} total wins · ${profile.losses||0} total losses<br>${SUPERSTARS[selectedSuperstar].name}: ${r.wins}-${r.losses}</div><div class="menu"><button class="primary" onclick="superstarSelect()">Exhibition Match</button><button class="secondary" onclick="deckBuilder(selectedSuperstar)">Playbook Builder</button><button class="secondary" onclick="showRosterStats()">Superstar Records</button><button class="secondary" onclick="showCards()">Card Collection</button><button class="secondary" onclick="showCompatibility()">Original Content Audit</button><button class="secondary" onclick="about()">About This Build</button></div></section>`}
function methodsFor(style){const base={Strike:2,Strength:2,Technical:2,Knowledge:1,Agility:1};if(style==='power')base.Strength=3;if(style==='brawler')base.Strike=3;if(style==='technical')base.Technical=3;if(style==='submission'){base.Technical=3;base.Knowledge=2}if(style==='agile')base.Agility=3;return base}
function emptyMomentum(){return Object.fromEntries(MOM_TYPES.map(x=>[x,0]))}
function totalMomentum(s){return MOM_TYPES.reduce((n,x)=>n+(s.momentum[x]||0),0)}
function createSide(slot,superKey,chosen=[]){const star=SUPERSTARS[superKey],deck=buildDeck(superKey,chosen);return{key:slot,superKey,name:star.name,maxHp:star.hp,hp:star.hp,momentum:emptyMomentum(),deck,hand:deck.splice(0,HAND_SIZE),discard:[],stun:0,abilityUsed:false,buffs:{nextDamage:0,nextDiscount:0,damageShield:0,momentumTax:0},inPlay:[],pins:0,kickouts:0,escapes:0,recoveries:0,counters:0,alignment:null,methods:methodsFor(star.style),zoneDamage:{Head:0,Arm:0,Leg:0,Body:0},pagesDrawn:0}}
function entrance(slot){return false}
function start(){const p=SUPERSTARS[selectedSuperstar],o=SUPERSTARS[selectedOpponent];state={player:createSide('player',selectedSuperstar,opening),cpu:createSide('cpu',selectedOpponent),control:'player',position:'Standing',pile:null,log:[],message:'The bell rings. Choose a legal page.',round:1,busy:false,hold:null,lastFinisher:null,reversalDepth:0,totalCounters:0};entrance('player');entrance('cpu');addLog(`${p.name} begins with 0 momentum.`);addLog(`${o.name} begins with 0 momentum.`);render()}
const side=k=>state[k],other=k=>k==='player'?'cpu':'player';
function drawTo(k,n=HAND_SIZE){const s=side(k);while(s.hand.length<n&&s.deck.length){s.hand.push(s.deck.shift());s.pagesDrawn++}}
function drawPages(k,n){const s=side(k);while(n-->0&&s.deck.length){s.hand.push(s.deck.shift());s.pagesDrawn++}}
function actualCost(card,key){const s=side(key);let limbTax=0;if(card.requirement==='Agility'&&s.zoneDamage.Leg>=10)limbTax++;if((card.requirement==='Strength'||card.requirement==='Strike')&&s.zoneDamage.Arm>=10)limbTax++;return Math.max(0,(Number(card.momentumCost)||0)-(s.buffs.nextDiscount||0)+limbTax+(s.buffs.momentumTax||0))}
function gainMomentum(k,type,amount){const s=side(k);type=MOM_TYPES.includes(type)?type:'Attitude';s.momentum[type]=Math.min(MAX_MOM,(s.momentum[type]||0)+Math.max(0,Number(amount)||0))}
function spendMomentum(k,amount,preferred){const s=side(k);let left=Math.max(0,Number(amount)||0);const order=['Attitude',preferred,...MOM_TYPES].filter((x,i,a)=>x&&a.indexOf(x)===i);for(const t of order){const use=Math.min(left,s.momentum[t]||0);s.momentum[t]-=use;left-=use;if(!left)break}return left===0}
function legalReason(card,key,asCounter=false){const s=side(key);if(state.busy&&!asCounter)return'Action resolving.';if(state.control!==key&&!asCounter)return'No match control.';if(state.hold)return'A submission is active.';if(s.stun>0)return`${s.name} is stunned.`;const cost=actualCost(card,key);if(cost>totalMomentum(s))return`Needs ${cost} total momentum (you have ${totalMomentum(s)}).`;if(card.minTurn&&state.round<card.minTurn)return`Playable after turn ${card.minTurn-1}.`;for(const [type,need] of Object.entries(card.momentumRequirements||{})){if((s.momentum[type]||0)<need)return`Needs ${need} ${type} momentum.`;}if(card.counterOnly&&!asCounter)return'Counter only.';if(card.face&&s.alignment==='Heel')return'Face page conflicts with Heel.';if(card.heel&&s.alignment==='Face')return'Heel page conflicts with Face.';if(card.requirement&&!s.methods[card.requirement])return`Needs ${card.requirement}.`;if(!asCounter&&card.position!=='Any'&&card.position!==state.position)return`Needs ${card.position}; now ${state.position}.`;return''}
const isLegal=(c,k)=>!legalReason(c,k);
function removeCard(k,c){const s=side(k),i=s.hand.findIndex(x=>x.instance===c.instance);if(i>=0)s.hand.splice(i,1);s.discard.push(c)}
function addLog(t){state.log.unshift(t);state.log=state.log.slice(0,10)}
function findCounter(k,attack){if(attack.uncounterable)return null;const s=side(k),positions=[attack.position,attack.originalMoveType,attack.setsPosition].filter(Boolean).map(x=>String(x).toLowerCase());const options=s.hand.filter(c=>c.cardClass!=='Gameplan'&&!legalReason(c,k,true)&&c.counters?.some(x=>positions.includes(String(x).toLowerCase())));return options.sort((a,b)=>(b.damage+b.momentumGain)-(a.damage+a.momentumGain))[0]||null}
function play(i){if(!state||state.busy)return;const c=state.player.hand[i];if(!c)return;const reason=legalReason(c,'player');if(reason){state.message=reason;render();return}resolveCard('player',c)}
function resolveCard(k,c){if(c.cardClass==='Momentum')return resolveMomentum(k,c);if(c.cardClass==='Gameplan')return resolveGameplan(k,c);resolveAttack(k,c)}
function resolveMomentum(k,c){state.busy=true;const s=side(k);removeCard(k,c);if(c.momentumChanges){for(const [type,n] of Object.entries(c.momentumChanges.gain||{}))gainMomentum(k,type,n);for(const [type,n] of Object.entries(c.momentumChanges.lose||{}))s.momentum[type]=Math.max(0,(s.momentum[type]||0)-n)}else gainMomentum(k,c.momentumType,c.momentumAmount||1);state.pile={card:c,owner:k,status:'MOMENTUM'};state.message=`${s.name} plays ${c.name} and applies its original momentum changes.`;addLog(state.message);drawTo(k);state.busy=false;render();if(k==='cpu')setTimeout(cpuTurn,450)}
function resolveGameplan(k,c){state.busy=true;const s=side(k);removeCard(k,c);spendMomentum(k,actualCost(c,k),c.method);if(c.effect==='nextDamage')s.buffs.nextDamage=2;if(c.effect==='nextDiscount')s.buffs.nextDiscount=2;if(c.face)s.alignment='Face';if(c.heel)s.alignment='Heel';const text=(c.description||'').toLowerCase();let duration=text.includes('remainder of the match')?999:text.includes('next 3')?3:text.includes('next two')||text.includes('next 2')?2:1;if(text.includes('reduce')&&text.includes('damage'))s.buffs.damageShield=Math.max(s.buffs.damageShield,2);if(text.includes('opponent')&&text.includes('momentum')&&text.includes('cost'))side(other(k)).buffs.momentumTax=Math.max(side(other(k)).buffs.momentumTax,1);s.inPlay.push({name:c.name,duration});gainMomentum(k,'Attitude',c.momentumGain||0);state.pile={card:c,owner:k,status:'IN PLAY'};state.message=`${s.name} sets ${c.name} (${duration===999?'match':duration+' rounds'}).`;addLog(`${s.name} places ${c.name} in play.`);drawTo(k);state.busy=false;render();if(k==='cpu')setTimeout(cpuTurn,550)}
function resolveAttack(k,c){state.busy=true;const dKey=other(k),a=side(k),d=side(dKey),cost=actualCost(c,k);removeCard(k,c);spendMomentum(k,cost,c.method);a.buffs.nextDiscount=0;state.pile={card:c,owner:k,status:'PLAYED'};state.message=`${a.name} plays ${c.name}. Checking for a counter…`;render();setTimeout(()=>resolveCounterWindow(k,c,0),420)}
function resolveCounterWindow(attacker,card,depth){const defender=other(attacker),a=side(attacker),d=side(defender),counter=findCounter(defender,card);if(counter&&depth<3){removeCard(defender,counter);d.counters++;state.totalCounters++;spendMomentum(defender,actualCost(counter,defender),counter.method);gainMomentum(defender,'Attitude',counter.momentumGain||0);state.pile={card:counter,owner:defender,status:`COUNTER ${depth+1}`};state.message=`COUNTER! ${d.name} answers with ${counter.name}.`;addLog(`${d.name} counters ${card.name} with ${counter.name}.`);render();const recounter=findCounter(attacker,counter);if(recounter&&depth<2&&Math.random()<(attacker==='player'?0.55:0.45)){setTimeout(()=>resolveCounterWindow(defender,counter,depth+1),420);return}state.control=defender;state.position=counter.setsPosition==='Same'?state.position:(counter.setsPosition||'Standing');finishResolution();return}applySuccessfulAttack(attacker,card)}
function applySuccessfulAttack(k,c){const dKey=other(k),a=side(k),d=side(dKey);let damage=c.damage+(a.buffs.nextDamage||0)+(c.damageBonus?Math.floor(Math.random()*(c.damageBonus+1)):0);a.buffs.nextDamage=0;if(d.buffs.damageShield){damage=Math.max(0,damage-d.buffs.damageShield)}if(a.zoneDamage.Head>=12)damage=Math.max(0,damage-1);d.hp=Math.max(0,d.hp-damage);const zone=/arm/i.test(c.name+c.description)?'Arm':/leg|ankle|knee/i.test(c.name+c.description)?'Leg':/head|ddt|neck/i.test(c.name+c.description)?'Head':'Body';d.zoneDamage[zone]+=damage;gainMomentum(k,'Attitude',c.momentumGain||0);if(c.face)a.alignment='Face';if(c.heel)a.alignment='Heel';if(c.drawEffect)drawPages(k,c.drawEffect);if(c.discardOpponent&&d.hand.length){const dropped=d.hand.splice(Math.floor(Math.random()*d.hand.length),1)[0];d.discard.push(dropped);addLog(`${d.name} discards ${dropped.name}.`)}if(c.discardSelf){for(let n=0;n<c.discardSelf&&a.hand.length;n++)a.discard.push(a.hand.pop())}if(c.recoverEffect&&a.discard.length){a.hand.push(a.discard.pop());a.recoveries++}state.position=c.setsPosition==='Same'?state.position:(c.setsPosition||'Standing');if(c.stun)d.stun=Math.max(d.stun,c.stun);if(c.conditionalStun&&!d.stun&&d.hand.length<a.hand.length)d.stun=1;state.control=k;state.pile={card:c,owner:k,status:'SUCCESS'};if(c.finisher)state.lastFinisher={by:k,round:state.round};addLog(`${a.name}'s ${c.name} succeeds for ${damage} damage to ${zone}.`);state.message=`SUCCESS! ${c.name} lands for ${damage} ${zone} damage.`;if(c.submission)return beginSubmission(k,c);finishResolution()}
function beginSubmission(k,c){state.hold={attacker:k,defender:other(k),card:c,turns:1,releaseChance:c.releaseChance||null};state.busy=false;state.position='Submission';state.message=`${side(k).name} locks in ${c.name}!`;addLog(`${side(k).name} applies ${c.name}.`);render();if(k==='cpu')setTimeout(cpuSubmission,700)}
function maintainSubmission(){if(!state?.hold||state.hold.attacker!=='player'||state.busy)return;submissionTick('player')}
function releaseSubmission(){if(!state?.hold||state.hold.attacker!=='player')return;const def=state.hold.defender;state.hold=null;state.control=def;state.position='Grounded';state.message='You release the hold. The opponent takes control.';addLog(`${state.player.name} releases the submission.`);render();setTimeout(cpuTurn,650)}
function submissionTick(k){const h=state.hold,a=side(k),d=side(h.defender);state.busy=true;if(h.releaseChance&&Math.random()<h.releaseChance){state.hold=null;state.control=h.defender;state.position='Standing';state.message=`${h.card.name} is released by its card effect.`;addLog(`${h.card.name} releases automatically.`);state.busy=false;render();if(state.control==='cpu')setTimeout(cpuTurn,650);return}const target=/arm/i.test(h.card.name+h.card.description)?'Arm':/leg|ankle|knee/i.test(h.card.name+h.card.description)?'Leg':'Body';const limbPenalty=Math.min(.28,d.zoneDamage[target]/45);const escapeChance=Math.min(.82,.20+totalMomentum(d)/35+d.hp/(d.maxHp*3)+h.turns*.07-limbPenalty);if(Math.random()<escapeChance){d.escapes++;spendMomentum(h.defender,3,'Attitude');state.hold=null;state.control=h.defender;state.position='Standing';state.message=`${d.name} escapes the submission and takes control!`;addLog(`${d.name} escapes ${h.card.name}.`);state.busy=false;render();if(state.control==='cpu')setTimeout(cpuTurn,650);return}const drain=3+h.turns;d.hp=Math.max(0,d.hp-drain);spendMomentum(h.defender,2,'Attitude');gainMomentum(k,'Attitude',2);h.turns++;state.message=`${h.card.name} stays locked in: ${drain} damage.`;addLog(`${a.name} maintains ${h.card.name} for ${drain} damage.`);state.busy=false;if(d.hp<=0||h.turns>=4&&d.hp<=8)return end(k==='player',`${d.name} submits`);render();if(k==='cpu')setTimeout(cpuSubmission,700)}
function cpuSubmission(){if(!state?.hold||state.hold.attacker!=='cpu')return;if(state.hold.turns>=3&&totalMomentum(state.cpu)<4){state.hold=null;state.control='player';state.position='Grounded';state.message=`${state.cpu.name} releases the hold. You regain control.`;addLog(`${state.cpu.name} releases the submission.`);render();return}submissionTick('cpu')}
function tickPersistent(){['player','cpu'].forEach(k=>{const s=side(k);s.inPlay=s.inPlay.filter(e=>{if(e.duration===999)return true;e.duration--;return e.duration>0});if(!s.inPlay.some(e=>/reduce/i.test(e.name)))s.buffs.damageShield=0;if(!side(other(k)).inPlay.some(e=>/momentum/i.test(e.name)&&/cost/i.test(e.name)))s.buffs.momentumTax=0})}
function finishResolution(){drawTo('player');drawTo('cpu');state.round++;tickPersistent();state.busy=false;const controller=side(state.control);if(controller.stun>0){controller.stun--;state.control=other(state.control);state.position='Standing';state.message=`${controller.name} is stunned and loses control.`;addLog(`${controller.name} loses control while stunned.`)}render();if(state.control==='cpu')setTimeout(cpuTurn,650)}
function pinChance(k){const d=side(other(k)),a=side(k);let chance=.08+(d.maxHp-d.hp)/60+totalMomentum(a)/100-totalMomentum(d)/140;if(state.lastFinisher?.by===k&&state.round-state.lastFinisher.round<=2)chance+=.28;return Math.max(.08,Math.min(.92,chance))}
function attemptPin(k='player'){if(!state||state.busy||state.control!==k||state.position!=='Grounded'||state.hold)return;state.busy=true;const a=side(k),d=side(other(k));a.pins++;const chance=pinChance(k);let count=1;state.message=`ONE! ${a.name} hooks the leg…`;render();const timer=setInterval(()=>{if(Math.random()>chance+(count-1)*.10){clearInterval(timer);d.kickouts++;gainMomentum(other(k),'Attitude',3+count);state.control=other(k);state.position='Standing';state.busy=false;state.message=`KICK OUT AT ${count}! ${d.name} survives and takes control.`;addLog(`${d.name} kicks out at ${count}.`);render();if(state.control==='cpu')setTimeout(cpuTurn,650);return}count++;if(count===2){state.message='TWO!';render();return}clearInterval(timer);end(k==='player',`${a.name} wins by pinfall`)},520)}
function useAbility(k='player'){if(!state||state.busy||state.control!==k)return;const s=side(k);if(s.abilityUsed)return;const star=SUPERSTARS[s.superKey];switch(star.style){case'power':s.buffs.nextDamage+=3;gainMomentum(k,'Attitude',3);break;case'submission':s.buffs.nextDiscount+=2;gainMomentum(k,'Attitude',4);state.position='In Close';break;case'agile':drawPages(k,2);gainMomentum(k,'Attitude',3);break;case'technical':s.buffs.nextDiscount+=3;drawPages(k,1);break;case'brawler':gainMomentum(k,'Attitude',5);state.position='In Close';break;default:gainMomentum(k,'Attitude',4);s.hp=Math.min(s.maxHp,s.hp+3)}s.abilityUsed=true;state.message=`${star.ability.toUpperCase()}: ${s.name} activates a Superstar ability.`;addLog(`${s.name} activates ${star.ability}.`);render();if(k==='cpu')setTimeout(cpuTurn,450)}

function recoverPage(k='player'){if(!state||state.busy||state.control!==k||state.hold)return;const s=side(k);if(!s.discard.length)return;if(totalMomentum(s)<3){state.message='Needs 3 momentum to recover a page.';render();return}const candidates=[...s.discard].sort((a,b)=>scoreCard(b,k)-scoreCard(a,k));const c=candidates[0],i=s.discard.indexOf(c);s.discard.splice(i,1);s.hand.push(c);spendMomentum(k,3,'Attitude');s.recoveries++;state.control=other(k);state.position='Standing';state.message=`${s.name} recovers ${c.name} and yields control.`;addLog(`${s.name} recovers ${c.name} from discard.`);render();if(state.control==='cpu')setTimeout(cpuTurn,600)}
function cpuTurn(){if(!state||state.busy||state.control!=='cpu'||state.hold)return;const s=state.cpu;if(!s.abilityUsed&&(s.hp<=20||totalMomentum(s)<=3))return useAbility('cpu');if(state.position==='Grounded'&&pinChance('cpu')>.50)return attemptPin('cpu');if(s.discard.length&&totalMomentum(s)>=8&&s.hand.length<3)return recoverPage('cpu');const legal=s.hand.filter(c=>isLegal(c,'cpu'));if(!legal.length){state.position='Standing';state.control='player';state.message=`${s.name} yields control.`;addLog(`${s.name} yields control.`);render();return}const c=[...legal].sort((a,b)=>scoreCard(b,'cpu')-scoreCard(a,'cpu'))[0];resolveCard('cpu',c)}
function scoreCard(c,k){const star=SUPERSTARS[side(k).superKey];let v=(c.damage||0)*2+(c.momentumGain||0)-actualCost(c,k);if(star.style==='submission'&&c.submission)v+=9;if(star.style==='power'&&c.requirement==='Strength')v+=5;if(star.style==='agile'&&c.requirement==='Agility')v+=5;if(star.style==='brawler'&&c.requirement==='Strike')v+=5;if(star.style==='technical'&&c.requirement==='Technical')v+=5;if(c.finisher)v+=12;if(c.submission&&side(other(k)).hp<18)v+=8;if(c.cardClass==='Gameplan')v+=side(k).buffs.nextDamage||side(k).buffs.nextDiscount?-5:3;return v}
function yieldControl(){if(!state||state.busy||state.control!=='player'||state.hold)return;state.control='cpu';state.position='Standing';state.message='You yield match control.';addLog(`${state.player.name} yields control.`);render();setTimeout(cpuTurn,650)}
function momentumLine(s){return MOM_TYPES.map(t=>`${t[0]}:${s.momentum[t]||0}`).join(' · ')}
function wrestler(k){const s=side(k),zones=Object.entries(s.zoneDamage).map(([z,v])=>`${z[0]}:${v}`).join(' ');return`<div class="wrestler ${k==='cpu'?'right':''}">${artImg(starArt(s.superKey),'wrestlerPortrait',s.name)}<div class="name">${s.name}</div><small>HP ${s.hp}/${s.maxHp} · TOTAL MOM ${totalMomentum(s)} · HAND ${s.hand.length}</small><small class="zones">${momentumLine(s)}</small><div class="meter"><i style="width:${s.hp/s.maxHp*100}%"></i></div><small class="zones">${zones}</small>${s.inPlay.length?`<small class="inplay">IN PLAY: ${s.inPlay.map(x=>esc(x.name)).join(', ')}</small>`:''}${s.stun?`<span class="stun">STUN ${s.stun}</span>`:''}<span class="abilityState">${s.abilityUsed?'ABILITY USED':'ABILITY READY'}</span></div>`}
function render(){if(!state)return;const p=state.player,legalCount=p.hand.filter(c=>isLegal(c,'player')).length,pin=state.control==='player'&&state.position==='Grounded'&&!state.hold;app.innerHTML=`<section class="screen arena"><div class="topbar"><button class="secondary compact" onclick="home()">Quit</button><b>EXHIBITION · ${VERSION}</b><span class="tag control">${state.control==='player'?'YOU CONTROL':'OPPONENT CONTROLS'}</span></div><div class="status">${wrestler('player')}${wrestler('cpu')}</div><div class="positionbar"><span>MATCH POSITION</span><strong>${state.position}</strong><span>ROUND ${state.round}</span></div><div class="ring"><div class="pile ${state.pile?state.pile.owner:''}">${state.pile?`${artImg(cardArt(state.pile.card),'pileArt',state.pile.card.name)}<span class="result">${state.pile.status}</span><b>${esc(state.pile.card.name)}</b><small>${state.pile.card.cardClass} · ${state.pile.card.damage} damage</small>`:'PLAY PILE'}</div></div><div class="message">${esc(state.message)}</div>${state.hold?submissionPanel():`<div class="actions"><button class="secondary" onclick="useAbility()" ${state.control!=='player'||state.busy||p.abilityUsed?'disabled':''}>${esc(SUPERSTARS[p.superKey].ability)}</button><button class="secondary" onclick="attemptPin()" ${pin?'':'disabled'}>Attempt Pin</button><button class="secondary" onclick="recoverPage()" ${state.control!=='player'||state.busy||!p.discard.length||totalMomentum(p)<3?'disabled':''}>Recover Page (3)</button><button class="secondary" onclick="yieldControl()" ${state.control!=='player'||state.busy?'disabled':''}>Yield Control</button><span>${legalCount} legal</span></div><div class="hand">${p.hand.map((c,i)=>cardHtml(c,i)).join('')}</div>`}<details class="matchlog"><summary>Match Log</summary>${state.log.map(x=>`<p>${esc(x)}</p>`).join('')}</details><div class="footer">v0.9.7 compatibility pass 5: original defensive counters and cancellation rules expanded.</div></section>`}
function submissionPanel(){const h=state.hold,isPlayer=h.attacker==='player';return`<div class="submissionPanel"><b>${esc(h.card.name)} · HOLD ${h.turns}</b><p>${esc(side(h.attacker).name)} is maintaining the submission on ${esc(side(h.defender).name)}.</p>${isPlayer?`<div class="actions"><button class="primary" onclick="maintainSubmission()">Maintain Hold</button><button class="secondary" onclick="releaseSubmission()">Release / Yield</button></div>`:'<p>The Rock is deciding whether to maintain the hold…</p>'}</div>`}
function cardHtml(c,i){const reason=legalReason(c,'player'),ok=!reason,cost=actualCost(c,'player');return`<article class="card ${ok?'playable':'locked'} class-${c.cardClass.toLowerCase()}">${artImg(cardArt(c),'cardArt',c.name)}<div class="cardhead"><h3>${esc(c.name)}</h3><span class="tag">${esc(c.cardClass)}</span></div><div class="position">PLAY: ${esc(c.position)}${c.setsPosition!=='Same'?` → ${esc(c.setsPosition)}`:''}</div><p>${esc(c.description)}</p>${c.counters?.length?`<div class="counter">COUNTERS: ${c.counters.map(esc).join(', ')}</div>`:''}<div class="stats"><span>DMG ${c.damage}</span><span>${c.cardClass==='Momentum'?esc(c.momentumType)+' +'+(c.momentumAmount||1):'ATT +'+(c.momentumGain||0)}</span><span>COST ${cost}</span></div><button onclick="play(${i})" ${ok?'':'disabled'}>${ok?'Play Page':esc(reason)}</button></article>`}
function end(win,reason){const winner=win?state.player:state.cpu;state.busy=true;if(win)profile.wins=(profile.wins||0)+1;else profile.losses=(profile.losses||0)+1;profile.stats=profile.stats||{};const ps=profile.stats[state.player.superKey]||{wins:0,losses:0,matches:0};ps.matches++;if(win)ps.wins++;else ps.losses++;profile.stats[state.player.superKey]=ps;saveProfile();setTimeout(()=>{app.innerHTML=`<section class="screen resultScreen"><div class="logo">${win?'VICTORY':'DEFEAT'}</div><div class="sub">${esc(reason||`${winner.name} wins the match`)}</div><div class="resultStats"><div><b>${state.player.hp}</b><span>${esc(state.player.name)} HP</span></div><div><b>${state.cpu.hp}</b><span>${esc(state.cpu.name)} HP</span></div><div><b>${state.round}</b><span>Rounds</span></div><div><b>${state.player.pins}</b><span>Your Pins</span></div><div><b>${state.player.kickouts}</b><span>Kickouts</span></div><div><b>${state.player.counters}</b><span>Counters</span></div><div><b>${state.player.recoveries}</b><span>Recoveries</span></div></div><div class="menu"><button class="primary" onclick="start()">Rematch</button><button class="secondary" onclick="superstarSelect()">New Match</button><button class="secondary" onclick="home()">Main Menu</button></div></section>`},180)}
function showCards(){app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>CARD LIBRARY</b><span>${cards.length}</span></div><div class="library">${cards.map(c=>`<article class="card class-${c.cardClass.toLowerCase()}"><div class="cardhead"><h3>${esc(c.name)}</h3><span class="tag">${esc(c.cardClass)}</span></div><div class="position">${esc(c.position)} → ${esc(c.setsPosition)}</div><p>${esc(c.description)}</p><div class="stats"><span>DMG ${c.damage}</span><span>${c.cardClass==='Momentum'?esc(c.momentumType)+' +'+(c.momentumAmount||1):'ATT +'+(c.momentumGain||0)}</span><span>COST ${c.momentumCost}</span></div></article>`).join('')}</div></section>`}
function about(){app.innerHTML=`<section class="screen"><div class="menu about"><div class="logo">${VERSION}</div><p><b>Complete Match Rules</b></p><p>This build adds reversal chains, limb-specific consequences, submission resistance, staged three-count pins, persistent in-play pages, page recovery, temporary modifiers and style-aware AI.</p><p>All progress is stored locally on this device.</p><button class="primary" onclick="home()">Return</button></div></section>`}
function showRosterStats(){app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>SUPERSTAR RECORDS</b><span>${VERSION}</span></div><div class="superGrid">${Object.values(SUPERSTARS).map(s=>{const r=recordFor(s.key);return`<article class="superCard">${artImg(starArt(s.key),'superPortrait',s.name)}<h2>${esc(s.name)}</h2><p>${esc(s.ability)}</p><p>${r.wins} wins · ${r.losses} losses · ${r.matches} matches</p><button class="secondary" onclick="deckBuilder('${s.key}')">View Playbook</button></article>`}).join('')}</div></section>`}
function superstarSelect(){app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>SELECT SUPERSTAR</b><span>${VERSION}</span></div><div class="superGrid">${Object.values(SUPERSTARS).map(s=>`<article class="superCard ${selectedSuperstar===s.key?'selected':''}">${artImg(starArt(s.key),'superPortrait',s.name)}<h2>${esc(s.name)}</h2><p>${esc(s.ability)}</p><p>${s.hp} HP · ${esc(s.style.toUpperCase())}</p><button class="primary" onclick="chooseSuperstar('${s.key}')">Select</button><button class="secondary" onclick="deckBuilder('${s.key}')">Edit Playbook</button></article>`).join('')}</div></section>`}
function chooseSuperstar(key){selectedSuperstar=key;opponentSelect()}
function opponentSelect(){const options=Object.values(SUPERSTARS).filter(s=>s.key!==selectedSuperstar);app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="superstarSelect()">Back</button><b>SELECT OPPONENT</b><span>${SUPERSTARS[selectedSuperstar].name}</span></div><div class="menu"><button class="primary" onclick="randomOpponent()">Random Opponent</button></div><div class="superGrid">${options.map(s=>`<article class="superCard">${artImg(starArt(s.key),'superPortrait',s.name)}<h2>${esc(s.name)}</h2><p>${esc(s.ability)}</p><p>${s.hp} HP · ${esc(s.style.toUpperCase())}</p><button class="secondary" onclick="setOpponent('${s.key}')">Choose Opponent</button></article>`).join('')}</div></section>`}
function randomOpponent(){const keys=Object.keys(SUPERSTARS).filter(k=>k!==selectedSuperstar);setOpponent(keys[Math.floor(Math.random()*keys.length)])}
function setOpponent(key){selectedOpponent=key;openingHand(selectedSuperstar)}
function openingHand(key){selectedSuperstar=key;const deck=buildDeck(key),candidates=deck.slice(0,8);opening=[];app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="superstarSelect()">Back</button><b>CHOOSE OPENING 5</b><span id="openCount">0 / 5</span></div><p class="instruction">Choose five starting pages. The remaining playbook will be shuffled.</p><div class="library openingGrid">${candidates.map((c,i)=>`<article class="card class-${c.cardClass.toLowerCase()}" id="open-${i}" onclick="toggleOpening(${i},'${c.id}')"><div class="cardhead"><h3>${esc(c.name)}</h3><span class="tag">${esc(c.cardClass)}</span></div><div class="position">${esc(c.position)} → ${esc(c.setsPosition)}</div><p>${esc(c.description)}</p><div class="stats"><span>DMG ${c.damage}</span><span>${c.cardClass==='Momentum'?esc(c.momentumType)+' +'+(c.momentumAmount||1):'ATT +'+(c.momentumGain||0)}</span><span>COST ${c.momentumCost}</span></div></article>`).join('')}</div><div class="stickyAction"><button class="primary" id="beginBtn" disabled onclick="start()">Begin Match</button></div></section>`}
function toggleOpening(i,id){const el=document.querySelector(`#open-${i}`),at=opening.indexOf(id);if(at>=0){opening.splice(at,1);el.classList.remove('chosen')}else if(opening.length<5){opening.push(id);el.classList.add('chosen')}document.querySelector('#openCount').textContent=`${opening.length} / 5`;document.querySelector('#beginBtn').disabled=opening.length!==5}
function countInDeck(ids,id){return ids.filter(x=>x===id).length}
function deckBuilder(key='player'){selectedSuperstar=key;const pool=poolFor(key),ids=[...deckIds(key)];profile.decks[key]=ids;const draw=()=>{app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>${SUPERSTARS[key].name} PLAYBOOK</b><span>${ids.length} pages</span></div><p class="instruction">Minimum 25 pages for this prototype. Limit 3 copies per page and 1 Trademark.</p><div class="deckSummary"><button class="secondary compact" onclick="resetDeck('${key}')">Reset Default</button><button class="primary compact" ${ids.length<25?'disabled':''} onclick="saveDeck('${key}')">Save Playbook</button></div><div class="library">${pool.map(c=>{const n=countInDeck(ids,c.id),limit=c.cardClass==='Trademark'?1:3;return`<article class="card class-${c.cardClass.toLowerCase()}"><div class="cardhead"><h3>${esc(c.name)}</h3><span class="tag">${n} / ${limit}</span></div><div class="position">${esc(c.position)} → ${esc(c.setsPosition)}</div><p>${esc(c.description)}</p><div class="stats"><span>DMG ${c.damage}</span><span>${c.cardClass==='Momentum'?esc(c.momentumType)+' +'+(c.momentumAmount||1):'ATT +'+(c.momentumGain||0)}</span><span>COST ${c.momentumCost}</span></div><div class="qty"><button onclick="changeDeck('${key}','${c.id}',-1)" ${n===0?'disabled':''}>−</button><b>${n}</b><button onclick="changeDeck('${key}','${c.id}',1)" ${n>=limit?'disabled':''}>+</button></div></article>`}).join('')}</div></section>`};window._drawDeck=draw;draw()}
function changeDeck(key,id,delta){const ids=profile.decks[key]||[];if(delta<0){const i=ids.indexOf(id);if(i>=0)ids.splice(i,1)}else{const c=poolFor(key).find(x=>x.id===id),limit=c?.cardClass==='Trademark'?1:3;if(countInDeck(ids,id)<limit)ids.push(id)}profile.decks[key]=ids;window._drawDeck()}
function saveDeck(key){if((profile.decks[key]||[]).length<25)return;saveProfile();state=null;home()}
function resetDeck(key){profile.decks[key]=defaultDeckIds(key);saveProfile();deckBuilder(key)}


/* v0.9.0 complete game shell */
function ensureProfile(){profile.decks=profile.decks||{};profile.stats=profile.stats||{};profile.matchHistory=profile.matchHistory||[];profile.missions=profile.missions||{};profile.settings=Object.assign({sound:true,animations:true,confirmReset:true},profile.settings||{});profile.credits=profile.credits||0;profile.xp=profile.xp||0}
function home(){ensureProfile();state=null;if(profile.firstLaunch)return firstLaunch();const r=recordFor(selectedSuperstar);app.innerHTML=`<section class="screen home gameHome"><div class="logo">WITH AUTHORITY!</div><div class="sub">Private mobile preservation build · ${VERSION}<br><b>LEVEL ${1+Math.floor(profile.xp/100)}</b> · ${profile.xp} XP · ${profile.credits} credits<br>${profile.wins||0} wins · ${profile.losses||0} losses · ${SUPERSTARS[selectedSuperstar].name} ${r.wins}-${r.losses}</div><div class="menu mainMenu"><button class="primary" onclick="superstarSelect()">Exhibition</button><button class="primary" onclick="practiceMenu()">Practice Missions</button><button class="secondary" onclick="playbookHub()">Playbook Manager</button><button class="secondary" onclick="showCards()">Card Collection</button><button class="secondary" onclick="showCompatibility()">Original Content Audit</button><button class="secondary" onclick="setBrowser()">Sets & Expansions</button><button class="secondary" onclick="showRosterStats()">Superstar Records</button><button class="secondary" onclick="showMatchHistory()">Match History</button><button class="secondary" onclick="settingsMenu()">Settings & Saves</button><button class="secondary" onclick="about()">About This Build</button></div></section>`}
function firstLaunch(){app.innerHTML=`<section class="screen welcome"><div class="logo">WITH AUTHORITY!</div><div class="welcomeCard"><h1>WELCOME</h1><p>This private mobile recreation stores all progress locally on this device.</p><p>Build playbooks, complete practice missions, earn credits and play Exhibition matches with the original mobile rules engine.</p><button class="primary" onclick="completeFirstLaunch()">Enter The Game</button></div></section>`}
function completeFirstLaunch(){profile.firstLaunch=false;saveProfile();home()}
function playbookHub(){app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>PLAYBOOK MANAGER</b><span>${VERSION}</span></div><p class="instruction">Choose a Superstar to inspect or edit their saved playbook.</p><div class="superGrid">${Object.values(SUPERSTARS).map(s=>`<article class="superCard">${artImg(starArt(s.key),'superPortrait',s.name)}<h2>${esc(s.name)}</h2><p>${deckIds(s.key).length} pages · ${esc(s.style.toUpperCase())}</p><button class="primary" onclick="deckBuilder('${s.key}')">Open Playbook</button></article>`).join('')}</div></section>`}
function practiceMenu(){const missions=[{id:'control',name:'Take Control',text:'Win as Stone Cold against Triple H.',p:'austin',o:'tripleh',reward:50},{id:'submission',name:'Submission Specialist',text:'Win as Kurt Angle against Chris Jericho.',p:'angle',o:'jericho',reward:75},{id:'giant',name:'Slay The Giant',text:'Defeat Big Show as Spike Dudley.',p:'spike',o:'bigshow',reward:100}];app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>PRACTICE MISSIONS</b><span>${Object.keys(profile.missions).length}/3</span></div><div class="missionGrid">${missions.map(m=>`<article class="mission ${profile.missions[m.id]?'complete':''}"><h2>${m.name}</h2><p>${m.text}</p><b>${profile.missions[m.id]?'COMPLETED':m.reward+' credits'}</b><button class="primary" onclick="startMission('${m.id}','${m.p}','${m.o}',${m.reward})">${profile.missions[m.id]?'Replay':'Start Mission'}</button></article>`).join('')}</div></section>`}
let activeMission=null;
function startMission(id,p,o,reward){activeMission={id,reward};selectedSuperstar=p;selectedOpponent=o;openingHand(p)}
function setBrowser(){const groups={};cards.forEach(c=>{const set=c.sourceSet||c.set||c.expansion||((c.modifiers||'').match(/(?:2E|EX\d|X8|LE|Tourn|SS2002)/i)||['Core'])[0];groups[set]=groups[set]||[];groups[set].push(c)});app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>SETS & EXPANSIONS</b><span>${Object.keys(groups).length}</span></div><div class="setGrid">${Object.entries(groups).sort((a,b)=>b[1].length-a[1].length).map(([n,list])=>`<article class="setCard"><h2>${esc(n)}</h2><strong>${list.length} pages</strong><p>${list.filter(c=>c.cardClass==='Trademark').length} Trademarks · ${list.filter(c=>c.cardClass==='Submission').length} Submissions</p><button class="secondary" onclick="showSet('${String(n).replace(/'/g,"\\'")}')">Browse Set</button></article>`).join('')}</div></section>`}
function showSet(name){const list=cards.filter(c=>(c.sourceSet||c.set||c.expansion||((c.modifiers||'').match(/(?:2E|EX\d|X8|LE|Tourn|SS2002)/i)||['Core'])[0])===name);app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="setBrowser()">Back</button><b>${esc(name)}</b><span>${list.length}</span></div><div class="library">${list.map(c=>libraryCard(c)).join('')}</div></section>`}
function libraryCard(c){return`<article class="card class-${c.cardClass.toLowerCase()}">${artImg(cardArt(c),'cardArt',c.name)}<div class="cardhead"><h3>${esc(c.name)}</h3><span class="tag">${esc(c.cardClass)}</span></div><div class="position">${esc(c.position)} → ${esc(c.setsPosition)}</div><p>${esc(c.description)}</p><div class="stats"><span>DMG ${c.damage}</span><span>${c.cardClass==='Momentum'?esc(c.momentumType)+' +'+(c.momentumAmount||1):'ATT +'+(c.momentumGain||0)}</span><span>COST ${c.momentumCost}</span></div></article>`}
function showCards(){const types=['All',...new Set(cards.map(c=>c.cardClass))];app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>CARD COLLECTION</b><span>${cards.length}</span></div><div class="filterbar">${types.map(t=>`<button class="secondary compact" onclick="filterCards('${t}')">${esc(t)}</button>`).join('')}</div><input id="cardSearch" class="search" placeholder="Search pages..." oninput="filterCards(document.querySelector('.filterbar .active')?.dataset.type||'All')"><div id="cardLibrary" class="library"></div></section>`;filterCards('All')}
function filterCards(type){document.querySelectorAll('.filterbar button').forEach(b=>{b.classList.toggle('active',b.textContent===type);b.dataset.type=b.textContent});const q=(document.querySelector('#cardSearch')?.value||'').toLowerCase();const list=cards.filter(c=>(type==='All'||c.cardClass===type)&&(`${c.name} ${c.description} ${c.owner||''}`).toLowerCase().includes(q));document.querySelector('#cardLibrary').innerHTML=list.map(c=>libraryCard(c)).join('')||'<p>No matching pages.</p>'}
function showMatchHistory(){ensureProfile();app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>MATCH HISTORY</b><span>${profile.matchHistory.length}</span></div><div class="history">${profile.matchHistory.length?profile.matchHistory.map(h=>`<article><b class="${h.win?'win':'loss'}">${h.win?'WIN':'LOSS'}</b><h3>${esc(h.player)} vs ${esc(h.cpu)}</h3><p>${esc(h.reason)} · ${h.rounds} rounds</p><small>${esc(h.date)}</small></article>`).join(''):'<p class="instruction">No completed matches yet.</p>'}</div></section>`}
function settingsMenu(){ensureProfile();app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>SETTINGS & SAVES</b><span>${VERSION}</span></div><div class="settings"><label><span>Sound</span><input type="checkbox" ${profile.settings.sound?'checked':''} onchange="toggleSetting('sound',this.checked)"></label><label><span>Animations</span><input type="checkbox" ${profile.settings.animations?'checked':''} onchange="toggleSetting('animations',this.checked)"></label><label><span>Confirm reset</span><input type="checkbox" ${profile.settings.confirmReset?'checked':''} onchange="toggleSetting('confirmReset',this.checked)"></label><button class="secondary" onclick="exportSave()">Export Save</button><label class="secondary importBtn">Import Save<input type="file" accept="application/json" onchange="importSave(this.files[0])"></label><button class="danger" onclick="resetProgress()">Reset All Progress</button></div></section>`}
function toggleSetting(k,v){profile.settings[k]=v;saveProfile()}
function exportSave(){const blob=new Blob([JSON.stringify(profile,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='with-authority-mobile-save-v098.json';a.click();URL.revokeObjectURL(a.href)}
function importSave(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result);if(!parsed||typeof parsed!=='object')throw Error();profile=parsed;ensureProfile();saveProfile();alert('Save imported successfully.');home()}catch{alert('That save file could not be imported.')}};r.readAsText(file)}
function resetProgress(){if(profile.settings.confirmReset&&!confirm('Reset all With Authority Mobile progress on this device?'))return;localStorage.removeItem(STORE);profile={decks:{},wins:0,losses:0,stats:{},credits:0,xp:0,matchHistory:[],missions:{},firstLaunch:true,settings:{sound:true,animations:true,confirmReset:true}};home()}
function about(){app.innerHTML=`<section class="screen"><div class="menu about"><div class="logo">${VERSION}</div><p><b>Full Card Compatibility Pass 6</b></p><p>This build adds verified alternate-edition move pages whose original text and behaviour match already-supported source implementations. No unresolved card effect has been approximated.</p><p>All progress remains local to this device unless you export the save manually.</p><button class="primary" onclick="home()">Return</button></div></section>`}
function end(win,reason){const winner=win?state.player:state.cpu;state.busy=true;ensureProfile();if(win)profile.wins++;else profile.losses++;profile.stats=profile.stats||{};const ps=profile.stats[state.player.superKey]||{wins:0,losses:0,matches:0};ps.matches++;if(win)ps.wins++;else ps.losses++;profile.stats[state.player.superKey]=ps;const reward=win?25:10;profile.credits+=reward;profile.xp+=win?30:15;if(activeMission&&win&&!profile.missions[activeMission.id]){profile.missions[activeMission.id]=true;profile.credits+=activeMission.reward;profile.xp+=50}profile.matchHistory.unshift({win,player:state.player.name,cpu:state.cpu.name,reason:reason||`${winner.name} wins the match`,rounds:state.round,date:new Date().toLocaleString()});profile.matchHistory=profile.matchHistory.slice(0,50);saveProfile();const missionBonus=activeMission&&win?activeMission.reward:0;activeMission=null;setTimeout(()=>{app.innerHTML=`<section class="screen resultScreen"><div class="logo">${win?'VICTORY':'DEFEAT'}</div><div class="sub">${esc(reason||`${winner.name} wins the match`)}<br><b>+${reward} credits · +${win?30:15} XP${missionBonus?` · Mission +${missionBonus}`:''}</b></div><div class="resultStats"><div><b>${state.player.hp}</b><span>${esc(state.player.name)} HP</span></div><div><b>${state.cpu.hp}</b><span>${esc(state.cpu.name)} HP</span></div><div><b>${state.round}</b><span>Rounds</span></div><div><b>${state.player.pins}</b><span>Your Pins</span></div><div><b>${state.player.kickouts}</b><span>Kickouts</span></div><div><b>${state.player.counters}</b><span>Counters</span></div><div><b>${state.player.recoveries}</b><span>Recoveries</span></div></div><div class="menu"><button class="primary" onclick="start()">Rematch</button><button class="secondary" onclick="superstarSelect()">New Match</button><button class="secondary" onclick="home()">Main Menu</button></div></section>`},profile.settings.animations?180:0)}

async function showCompatibility(){
  const [m,r]=await Promise.all([fetch('data/compatibility-manifest.json').then(x=>x.json()),fetch('data/card-compatibility-report.json').then(x=>x.json())]);
  const rows=r.filter(x=>x.status!=='non_playable_or_duplicate').slice(0,250);
  app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>ORIGINAL CONTENT AUDIT</b><span>${m.totalOriginalFiles}</span></div><div class="resultStats"><div><b>${m.counts.fully_supported}</b><span>Supported</span></div><div><b>${m.counts.partially_supported}</b><span>Rule Work</span></div><div><b>${m.counts.disabled}</b><span>Disabled</span></div><div><b>${m.counts.non_playable_or_duplicate}</b><span>Other</span></div></div><p class="instruction">${m.playableRecords} playable records. ${m.newlyEnabledOriginalSpecials||m.newlyEnabledOriginalMoves||0} additional original pages were enabled in this pass. Audio and online systems are excluded.</p><div class="library">${rows.map(x=>`<article class="card"><div class="cardhead"><h3>${esc(x.name||x.sourceFile)}</h3><span class="tag">${esc(x.status.replaceAll('_',' '))}</span></div><div class="position">${esc(x.category)} · ${esc(x.sourceFile)}</div><p>${esc((x.ruleFamilies||[]).join(', ')||'No recognised rule family')}</p></article>`).join('')}</div></section>`
}
