const app=document.querySelector('#app');let cards=[],state;
fetch('data/demo-cards.json').then(r=>r.json()).then(x=>{cards=x;home()});
function home(){app.innerHTML=`<section class="screen"><div class="logo">WITH AUTHORITY!</div><div class="sub">Private mobile preservation prototype · v0.1.0</div><div class="menu"><button class="primary" onclick="start()">Exhibition Match</button><button class="secondary" onclick="showCards()">Extracted Card Library</button><button class="secondary" onclick="about()">About This Build</button></div></section>`}
function start(){const deck=[...cards,...cards].sort(()=>Math.random()-.5);state={pHP:40,cHP:40,pMom:8,cMom:8,deck,hand:deck.splice(0,5),pile:null,turn:'player',msg:'You are in control. Choose a playable page.'};render()}
function draw(){if(state.deck.length)state.hand.push(state.deck.shift())}
function play(i){if(state.turn!=='player')return;let c=state.hand[i];if(c.momentumCost>state.pMom){state.msg='Not enough momentum.';render();return}state.pMom-=c.momentumCost;state.cHP=Math.max(0,state.cHP-(c.damage||2));state.pMom+=1;state.pile=c;state.hand.splice(i,1);draw();state.msg=`${c.name} connects for ${c.damage||2} damage.`;render();if(state.cHP<=0)return end(true);state.turn='cpu';setTimeout(cpu,650)}
function cpu(){let playable=cards.filter(c=>c.momentumCost<=state.cMom);let c=playable[Math.floor(Math.random()*playable.length)]||cards[0];state.cMom-=c.momentumCost;state.pHP=Math.max(0,state.pHP-(c.damage||2));state.cMom+=1;state.pile=c;state.msg=`Opponent answers with ${c.name}.`;state.turn='player';draw();render();if(state.pHP<=0)end(false)}
function render(){app.innerHTML=`<section class="screen arena"><div class="topbar"><button class="secondary" onclick="home()">Quit</button><b>EXHIBITION</b><span class="tag">${state.turn==='player'?'IN CONTROL':'OPPONENT'}</span></div><div class="status"><div class="wrestler"><div class="name">STONE COLD</div><small>HP ${state.pHP} · MOM ${state.pMom}</small><div class="meter"><i style="width:${state.pHP/40*100}%"></i></div></div><div class="wrestler" style="text-align:right"><div class="name">THE ROCK</div><small>HP ${state.cHP} · MOM ${state.cMom}</small><div class="meter"><i style="width:${state.cHP/40*100}%"></i></div></div></div><div class="ring"><div class="pile">${state.pile?`<b>${state.pile.name}</b><small>${state.pile.damage||2} damage</small>`:'PLAY PILE'}</div></div><div class="message">${state.msg}</div><div class="hand">${state.hand.map((c,i)=>`<article class="card ${c.momentumCost<=state.pMom&&state.turn==='player'?'playable':''}"><h3>${c.name}</h3><span class="tag">${c.method}</span><p>${c.description||'Original card definition extracted from the game archive.'}</p><div class="stats"><span>DMG ${c.damage||2}</span><span>COST ${c.momentumCost}</span></div><button onclick="play(${i})">Play Page</button></article>`).join('')}</div><div class="footer">Prototype engine: damage, momentum, control turns and original extracted card data. Reversals and full scripting are scheduled for the next pass.</div></section>`}
function end(win){setTimeout(()=>{app.innerHTML=`<section class="screen"><div class="logo">${win?'VICTORY':'DEFEAT'}</div><div class="sub">${win?'Stone Cold wins the test match.':'The Rock wins the test match.'}</div><div class="menu"><button class="primary" onclick="start()">Rematch</button><button class="secondary" onclick="home()">Main Menu</button></div></section>`},100)}
function showCards(){app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary" onclick="home()">Back</button><b>EXTRACTED CARDS</b><span>${cards.length}</span></div><div class="hand" style="flex-wrap:wrap;overflow:visible">${cards.map(c=>`<article class="card"><h3>${c.name}</h3><span class="tag">${c.method}</span><p>${c.description||'Definition extracted.'}</p><div class="stats"><span>DMG ${c.damage||0}</span><span>COST ${c.momentumCost}</span></div></article>`).join('')}</div></section>`}
function about(){app.innerHTML=`<section class="screen"><div class="menu"><div class="logo">v0.1.0</div><p>This first private test build proves that the original wrapped game files can be decoded and used by a modern touch interface.</p><p>The included match is intentionally a foundation build. It uses original extracted card records, while the complete script interpreter, reversals, playbook construction and converted visual assets remain to be integrated.</p><button class="primary" onclick="home()">Return</button></div></section>`}