'use strict';
const app=document.querySelector('#app');
let cards=[],state=null;
const VERSION='v0.4.0',MAX_HP=40,HAND_SIZE=5,MAX_MOM=20,STORE='wa-mobile-v040';
const SUPERSTARS={player:{key:'player',name:'STONE COLD',ability:'Bionic Redneck',entrance:'Glass Shatters'},cpu:{key:'cpu',name:'THE ROCK',ability:"People's Champion",entrance:'If You Smell'}};
let profile=loadProfile(),selectedSuperstar='player',opening=[];
function loadProfile(){try{return JSON.parse(localStorage.getItem(STORE))||{decks:{},wins:0,losses:0}}catch{return{decks:{},wins:0,losses:0}}}
function saveProfile(){localStorage.setItem(STORE,JSON.stringify(profile))}
fetch('data/demo-cards.json').then(r=>{if(!r.ok)throw new Error('Card data failed to load');return r.json()}).then(x=>{cards=x;home()}).catch(err=>app.innerHTML=`<section class="screen"><div class="logo">LOAD ERROR</div><p>${esc(err.message)}</p></section>`);
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function poolFor(key){return cards.filter(c=>!c.owner||c.owner===key).filter(c=>c.cardClass!=='Entrance')}
function defaultDeckIds(key){const pool=poolFor(key);let ids=[];for(let n=0;n<3;n++)pool.forEach(c=>{if(c.cardClass!=='Trademark'||!ids.includes(c.id))ids.push(c.id)});return ids.slice(0,30)}
function deckIds(key){return profile.decks[key]?.length?profile.decks[key]:defaultDeckIds(key)}
function buildDeck(key,chosenOpening=[]){const ids=deckIds(key),pool=poolFor(key),made=ids.map((id,i)=>{const c=pool.find(x=>x.id===id);return c?{...c,instance:`${key}-${i}-${Math.random()}`}:null}).filter(Boolean);const first=[];chosenOpening.forEach(id=>{const i=made.findIndex(c=>c.id===id);if(i>=0)first.push(made.splice(i,1)[0])});return [...first,...shuffle(made)]}
function home(){state=null;app.innerHTML=`<section class="screen home"><div class="logo">WITH AUTHORITY!</div><div class="sub">Private mobile preservation prototype · ${VERSION}<br>${profile.wins||0} wins · ${profile.losses||0} losses</div><div class="menu"><button class="primary" onclick="superstarSelect()">Exhibition Match</button><button class="secondary" onclick="deckBuilder(selectedSuperstar)">Playbook Builder</button><button class="secondary" onclick="showCards()">Card Collection</button><button class="secondary" onclick="about()">About This Build</button></div></section>`}
function createSide(key,name,chosen=[]){const deck=buildDeck(key,chosen);return{key,name,hp:MAX_HP,momentum:6,deck,hand:deck.splice(0,HAND_SIZE),discard:[],stun:0,abilityUsed:false,buffs:{nextDamage:0,nextDiscount:0},pins:0,escapes:0}}
function entrance(key){const c=cards.find(x=>x.cardClass==='Entrance'&&x.owner===key);if(c)side(key).momentum=Math.min(MAX_MOM,side(key).momentum+c.momentumGain)}
function start(){state={player:createSide('player','STONE COLD',opening),cpu:createSide('cpu','THE ROCK'),control:'player',position:'Standing',pile:null,log:[],message:'The bell rings. Choose a legal page.',round:1,busy:false,hold:null,lastFinisher:null};entrance('player');entrance('cpu');addLog('Glass shatters. Stone Cold enters with 9 momentum.');addLog('The Rock answers and enters with 9 momentum.');render()}
const side=k=>state[k],other=k=>k==='player'?'cpu':'player';
function drawTo(k,n=HAND_SIZE){const s=side(k);while(s.hand.length<n&&s.deck.length)s.hand.push(s.deck.shift())}
function actualCost(card,key){return Math.max(0,card.momentumCost-(side(key).buffs.nextDiscount||0))}
function legalReason(card,key){const s=side(key);if(state.busy)return'Action resolving.';if(state.control!==key)return'No match control.';if(state.hold)return'A submission is active.';if(s.stun>0)return`${s.name} is stunned.`;const cost=actualCost(card,key);if(cost>s.momentum)return`Needs ${cost} momentum.`;if(card.position!=='Any'&&card.position!==state.position)return`Needs ${card.position}; now ${state.position}.`;return''}
const isLegal=(c,k)=>!legalReason(c,k);
function removeCard(k,c){const s=side(k),i=s.hand.findIndex(x=>x.instance===c.instance);if(i>=0)s.hand.splice(i,1);s.discard.push(c)}
function addLog(t){state.log.unshift(t);state.log=state.log.slice(0,10)}
function findCounter(k,attack){const s=side(k),options=s.hand.filter(c=>c.cardClass!=='Gameplan'&&c.counters?.includes(attack.position)&&actualCost(c,k)<=s.momentum);return options.sort((a,b)=>actualCost(a,k)-actualCost(b,k))[0]||null}
function play(i){if(!state||state.busy)return;const c=state.player.hand[i];if(!c)return;const reason=legalReason(c,'player');if(reason){state.message=reason;render();return}resolveCard('player',c)}
function resolveCard(k,c){if(c.cardClass==='Gameplan')return resolveGameplan(k,c);resolveAttack(k,c)}
function resolveGameplan(k,c){state.busy=true;const s=side(k);removeCard(k,c);s.momentum-=actualCost(c,k);if(c.effect==='nextDamage')s.buffs.nextDamage=2;if(c.effect==='nextDiscount')s.buffs.nextDiscount=2;s.momentum=Math.min(MAX_MOM,s.momentum+c.momentumGain);state.pile={card:c,owner:k,status:'GAMEPLAN'};state.message=`${s.name} sets ${c.name}.`;addLog(`${s.name} plays ${c.name}.`);drawTo(k);state.busy=false;render();if(k==='cpu')setTimeout(cpuTurn,550)}
function resolveAttack(k,c){state.busy=true;const dKey=other(k),a=side(k),d=side(dKey),cost=actualCost(c,k);removeCard(k,c);a.momentum-=cost;a.buffs.nextDiscount=0;state.pile={card:c,owner:k,status:'PLAYED'};state.message=`${a.name} plays ${c.name}. Checking for a counter…`;render();setTimeout(()=>{const counter=findCounter(dKey,c);if(counter){removeCard(dKey,counter);d.momentum=Math.max(0,d.momentum-actualCost(counter,dKey));d.momentum=Math.min(MAX_MOM,d.momentum+(counter.momentumGain||2));state.control=dKey;state.position=counter.setsPosition==='Same'?state.position:(counter.setsPosition||'Standing');state.pile={card:counter,owner:dKey,status:'COUNTER'};state.message=`COUNTER! ${d.name} takes control with ${counter.name}.`;addLog(`${d.name} counters ${c.name} with ${counter.name}.`);finishResolution()}else{let damage=c.damage+(a.buffs.nextDamage||0);a.buffs.nextDamage=0;d.hp=Math.max(0,d.hp-damage);a.momentum=Math.min(MAX_MOM,a.momentum+(c.momentumGain||2));d.momentum=Math.min(MAX_MOM,d.momentum+1);state.position=c.setsPosition==='Same'?state.position:(c.setsPosition||'Standing');if(c.stun)d.stun=Math.max(d.stun,c.stun);state.control=k;state.pile={card:c,owner:k,status:'SUCCESS'};if(c.finisher)state.lastFinisher={by:k,round:state.round};addLog(`${a.name}'s ${c.name} succeeds for ${damage} damage.`);state.message=`SUCCESS! ${c.name} lands for ${damage} damage.`;if(c.submission)return beginSubmission(k,c);finishResolution()}},500)}
function beginSubmission(k,c){state.hold={attacker:k,defender:other(k),card:c,turns:1};state.busy=false;state.position='Submission';state.message=`${side(k).name} locks in ${c.name}!`;addLog(`${side(k).name} applies ${c.name}.`);render();if(k==='cpu')setTimeout(cpuSubmission,700)}
function maintainSubmission(){if(!state?.hold||state.hold.attacker!=='player'||state.busy)return;submissionTick('player')}
function releaseSubmission(){if(!state?.hold||state.hold.attacker!=='player')return;const def=state.hold.defender;state.hold=null;state.control=def;state.position='Grounded';state.message='You release the hold. The opponent takes control.';addLog('Stone Cold releases the submission.');render();setTimeout(cpuTurn,650)}
function submissionTick(k){const h=state.hold,a=side(k),d=side(h.defender);state.busy=true;const escapeChance=Math.min(.8,.18+d.momentum/35+d.hp/120+h.turns*.08);if(Math.random()<escapeChance){d.escapes++;d.momentum=Math.max(0,d.momentum-3);state.hold=null;state.control=h.defender;state.position='Standing';state.message=`${d.name} escapes the submission and takes control!`;addLog(`${d.name} escapes ${h.card.name}.`);state.busy=false;render();if(state.control==='cpu')setTimeout(cpuTurn,650);return}const drain=3+h.turns;d.hp=Math.max(0,d.hp-drain);d.momentum=Math.max(0,d.momentum-2);a.momentum=Math.min(MAX_MOM,a.momentum+2);h.turns++;state.message=`${h.card.name} stays locked in: ${drain} damage.`;addLog(`${a.name} maintains ${h.card.name} for ${drain} damage.`);state.busy=false;if(d.hp<=0||h.turns>=4&&d.hp<=8)return end(k==='player',`${d.name} submits`);render();if(k==='cpu')setTimeout(cpuSubmission,700)}
function cpuSubmission(){if(!state?.hold||state.hold.attacker!=='cpu')return;if(state.hold.turns>=3&&state.cpu.momentum<4){state.hold=null;state.control='player';state.position='Grounded';state.message='The Rock releases the hold. You regain control.';addLog('The Rock releases the submission.');render();return}submissionTick('cpu')}
function finishResolution(){drawTo('player');drawTo('cpu');state.round++;state.busy=false;const controller=side(state.control);if(controller.stun>0){controller.stun--;state.control=other(state.control);state.position='Standing';state.message=`${controller.name} is stunned and loses control.`;addLog(`${controller.name} loses control while stunned.`)}render();if(state.control==='cpu')setTimeout(cpuTurn,650)}
function pinChance(k){const d=side(other(k)),a=side(k);let chance=.08+(MAX_HP-d.hp)/60+a.momentum/100-d.momentum/140;if(state.lastFinisher?.by===k&&state.round-state.lastFinisher.round<=2)chance+=.28;return Math.max(.08,Math.min(.92,chance))}
function attemptPin(k='player'){if(!state||state.busy||state.control!==k||state.position!=='Grounded'||state.hold)return;state.busy=true;const a=side(k),d=side(other(k));a.pins++;const chance=pinChance(k);state.message=`${a.name} hooks the leg…`;render();setTimeout(()=>{if(Math.random()<chance)return end(k==='player',`${a.name} wins by pinfall`);d.momentum=Math.min(MAX_MOM,d.momentum+4);state.control=other(k);state.position='Standing';state.busy=false;state.message=`KICK OUT! ${d.name} survives and takes control.`;addLog(`${d.name} kicks out of ${a.name}'s pin attempt.`);render();if(state.control==='cpu')setTimeout(cpuTurn,650)},700)}
function useAbility(k='player'){if(!state||state.busy||state.control!==k)return;const s=side(k);if(s.abilityUsed)return;if(k==='player'){s.momentum=Math.min(MAX_MOM,s.momentum+5);state.position='In Close';state.message='BIONIC REDNECK: gain 5 momentum and move In Close.';addLog('Stone Cold activates Bionic Redneck.')}else{s.momentum=Math.min(MAX_MOM,s.momentum+4);s.hp=Math.min(MAX_HP,s.hp+3);state.message="PEOPLE'S CHAMPION: The Rock gains 4 momentum and recovers 3 HP.";addLog("The Rock activates People's Champion.")}s.abilityUsed=true;render();if(k==='cpu')setTimeout(cpuTurn,450)}
function cpuTurn(){if(!state||state.busy||state.control!=='cpu'||state.hold)return;const s=state.cpu;if(!s.abilityUsed&&(s.hp<=20||s.momentum<=3))return useAbility('cpu');if(state.position==='Grounded'&&pinChance('cpu')>.55)return attemptPin('cpu');const legal=s.hand.filter(c=>isLegal(c,'cpu'));if(!legal.length){s.momentum=Math.min(MAX_MOM,s.momentum+2);state.position='Standing';state.control='player';state.message='The Rock regroups and yields control.';addLog('The Rock gains 2 momentum and yields control.');render();return}const c=[...legal].sort((a,b)=>scoreCard(b,'cpu')-scoreCard(a,'cpu'))[0];resolveCard('cpu',c)}
function scoreCard(c,k){let v=(c.damage||0)*2+(c.momentumGain||0)-actualCost(c,k);if(c.finisher)v+=12;if(c.submission&&side(other(k)).hp<18)v+=8;if(c.cardClass==='Gameplan')v+=side(k).buffs.nextDamage||side(k).buffs.nextDiscount?-5:3;return v}
function yieldControl(){if(!state||state.busy||state.control!=='player'||state.hold)return;state.player.momentum=Math.min(MAX_MOM,state.player.momentum+2);state.control='cpu';state.position='Standing';state.message='You regroup, gain 2 momentum, and yield control.';addLog('Stone Cold regroups and yields control.');render();setTimeout(cpuTurn,650)}
function wrestler(k){const s=side(k);return`<div class="wrestler ${k==='cpu'?'right':''}"><div class="name">${s.name}</div><small>HP ${s.hp}/${MAX_HP} · MOM ${s.momentum} · HAND ${s.hand.length}</small><div class="meter"><i style="width:${s.hp/MAX_HP*100}%"></i></div>${s.stun?`<span class="stun">STUN ${s.stun}</span>`:''}<span class="abilityState">${s.abilityUsed?'ABILITY USED':'ABILITY READY'}</span></div>`}
function render(){if(!state)return;const p=state.player,legalCount=p.hand.filter(c=>isLegal(c,'player')).length,pin=state.control==='player'&&state.position==='Grounded'&&!state.hold;app.innerHTML=`<section class="screen arena"><div class="topbar"><button class="secondary compact" onclick="home()">Quit</button><b>EXHIBITION · ${VERSION}</b><span class="tag control">${state.control==='player'?'YOU CONTROL':'OPPONENT CONTROLS'}</span></div><div class="status">${wrestler('player')}${wrestler('cpu')}</div><div class="positionbar"><span>MATCH POSITION</span><strong>${state.position}</strong><span>ROUND ${state.round}</span></div><div class="ring"><div class="pile ${state.pile?state.pile.owner:''}">${state.pile?`<span class="result">${state.pile.status}</span><b>${esc(state.pile.card.name)}</b><small>${state.pile.card.cardClass} · ${state.pile.card.damage} damage</small>`:'PLAY PILE'}</div></div><div class="message">${esc(state.message)}</div>${state.hold?submissionPanel():`<div class="actions"><button class="secondary" onclick="useAbility()" ${state.control!=='player'||state.busy||p.abilityUsed?'disabled':''}>Bionic Redneck</button><button class="secondary" onclick="attemptPin()" ${pin?'':'disabled'}>Attempt Pin</button><button class="secondary" onclick="yieldControl()" ${state.control!=='player'||state.busy?'disabled':''}>Regroup +2</button><span>${legalCount} legal</span></div><div class="hand">${p.hand.map((c,i)=>cardHtml(c,i)).join('')}</div>`}<details class="matchlog"><summary>Match Log</summary>${state.log.map(x=>`<p>${esc(x)}</p>`).join('')}</details><div class="footer">Pins are available from Grounded. Submissions persist until escaped, released, or completed. Entrance, Gameplan and Trademark pages now use separate rules.</div></section>`}
function submissionPanel(){const h=state.hold,isPlayer=h.attacker==='player';return`<div class="submissionPanel"><b>${esc(h.card.name)} · HOLD ${h.turns}</b><p>${esc(side(h.attacker).name)} is maintaining the submission on ${esc(side(h.defender).name)}.</p>${isPlayer?`<div class="actions"><button class="primary" onclick="maintainSubmission()">Maintain Hold</button><button class="secondary" onclick="releaseSubmission()">Release / Yield</button></div>`:'<p>The Rock is deciding whether to maintain the hold…</p>'}</div>`}
function cardHtml(c,i){const reason=legalReason(c,'player'),ok=!reason,cost=actualCost(c,'player');return`<article class="card ${ok?'playable':'locked'} class-${c.cardClass.toLowerCase()}"><div class="cardhead"><h3>${esc(c.name)}</h3><span class="tag">${esc(c.cardClass)}</span></div><div class="position">PLAY: ${esc(c.position)}${c.setsPosition!=='Same'?` → ${esc(c.setsPosition)}`:''}</div><p>${esc(c.description)}</p>${c.counters?.length?`<div class="counter">COUNTERS: ${c.counters.map(esc).join(', ')}</div>`:''}<div class="stats"><span>DMG ${c.damage}</span><span>MOM +${c.momentumGain}</span><span>COST ${cost}</span></div><button onclick="play(${i})" ${ok?'':'disabled'}>${ok?'Play Page':esc(reason)}</button></article>`}
function end(win,reason){const winner=win?state.player:state.cpu;state.busy=true;if(win)profile.wins=(profile.wins||0)+1;else profile.losses=(profile.losses||0)+1;saveProfile();setTimeout(()=>{app.innerHTML=`<section class="screen resultScreen"><div class="logo">${win?'VICTORY':'DEFEAT'}</div><div class="sub">${esc(reason||`${winner.name} wins the match`)}</div><div class="resultStats"><div><b>${state.player.hp}</b><span>Stone Cold HP</span></div><div><b>${state.cpu.hp}</b><span>The Rock HP</span></div><div><b>${state.round}</b><span>Rounds</span></div><div><b>${state.player.pins}</b><span>Your Pins</span></div></div><div class="menu"><button class="primary" onclick="start()">Rematch</button><button class="secondary" onclick="home()">Main Menu</button></div></section>`},180)}
function showCards(){app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>CARD LIBRARY</b><span>${cards.length}</span></div><div class="library">${cards.map(c=>`<article class="card class-${c.cardClass.toLowerCase()}"><div class="cardhead"><h3>${esc(c.name)}</h3><span class="tag">${esc(c.cardClass)}</span></div><div class="position">${esc(c.position)} → ${esc(c.setsPosition)}</div><p>${esc(c.description)}</p><div class="stats"><span>DMG ${c.damage}</span><span>MOM +${c.momentumGain}</span><span>COST ${c.momentumCost}</span></div></article>`).join('')}</div></section>`}
function about(){app.innerHTML=`<section class="screen"><div class="menu about"><div class="logo">${VERSION}</div><p><b>Original Content & Playbook Systems</b></p><p>This build adds Superstar selection, independent saved playbooks, collection browsing, duplicate limits, opening-hand selection, and persistent local match records.</p><p>All progress is stored locally on this device.</p><button class="primary" onclick="home()">Return</button></div></section>`}

function superstarSelect(){app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>SELECT SUPERSTAR</b><span>${VERSION}</span></div><div class="superGrid"><article class="superCard selected"><h2>STONE COLD</h2><p>Bionic Redneck</p><p>Powerful strikes, close-range attacks and the Stone Cold Stunner.</p><button class="primary" onclick="openingHand('player')">Select</button><button class="secondary" onclick="deckBuilder('player')">Edit Playbook</button></article><article class="superCard lockedSuper"><h2>THE ROCK</h2><p>People's Champion</p><p>Available as the current CPU opponent. Player selection arrives with expanded Superstar support.</p><button class="secondary" disabled>CPU Opponent</button></article></div></section>`}
function openingHand(key){selectedSuperstar=key;const deck=buildDeck(key),candidates=deck.slice(0,8);opening=[];app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="superstarSelect()">Back</button><b>CHOOSE OPENING 5</b><span id="openCount">0 / 5</span></div><p class="instruction">Choose five starting pages. The remaining playbook will be shuffled.</p><div class="library openingGrid">${candidates.map((c,i)=>`<article class="card class-${c.cardClass.toLowerCase()}" id="open-${i}" onclick="toggleOpening(${i},'${c.id}')"><div class="cardhead"><h3>${esc(c.name)}</h3><span class="tag">${esc(c.cardClass)}</span></div><div class="position">${esc(c.position)} → ${esc(c.setsPosition)}</div><p>${esc(c.description)}</p><div class="stats"><span>DMG ${c.damage}</span><span>MOM +${c.momentumGain}</span><span>COST ${c.momentumCost}</span></div></article>`).join('')}</div><div class="stickyAction"><button class="primary" id="beginBtn" disabled onclick="start()">Begin Match</button></div></section>`}
function toggleOpening(i,id){const el=document.querySelector(`#open-${i}`),at=opening.indexOf(id);if(at>=0){opening.splice(at,1);el.classList.remove('chosen')}else if(opening.length<5){opening.push(id);el.classList.add('chosen')}document.querySelector('#openCount').textContent=`${opening.length} / 5`;document.querySelector('#beginBtn').disabled=opening.length!==5}
function countInDeck(ids,id){return ids.filter(x=>x===id).length}
function deckBuilder(key='player'){selectedSuperstar=key;const pool=poolFor(key),ids=[...deckIds(key)];profile.decks[key]=ids;const draw=()=>{app.innerHTML=`<section class="screen"><div class="topbar"><button class="secondary compact" onclick="home()">Back</button><b>${SUPERSTARS[key].name} PLAYBOOK</b><span>${ids.length} pages</span></div><p class="instruction">Minimum 25 pages for this prototype. Limit 3 copies per page and 1 Trademark.</p><div class="deckSummary"><button class="secondary compact" onclick="resetDeck('${key}')">Reset Default</button><button class="primary compact" ${ids.length<25?'disabled':''} onclick="saveDeck('${key}')">Save Playbook</button></div><div class="library">${pool.map(c=>{const n=countInDeck(ids,c.id),limit=c.cardClass==='Trademark'?1:3;return`<article class="card class-${c.cardClass.toLowerCase()}"><div class="cardhead"><h3>${esc(c.name)}</h3><span class="tag">${n} / ${limit}</span></div><div class="position">${esc(c.position)} → ${esc(c.setsPosition)}</div><p>${esc(c.description)}</p><div class="stats"><span>DMG ${c.damage}</span><span>MOM +${c.momentumGain}</span><span>COST ${c.momentumCost}</span></div><div class="qty"><button onclick="changeDeck('${key}','${c.id}',-1)" ${n===0?'disabled':''}>−</button><b>${n}</b><button onclick="changeDeck('${key}','${c.id}',1)" ${n>=limit?'disabled':''}>+</button></div></article>`}).join('')}</div></section>`};window._drawDeck=draw;draw()}
function changeDeck(key,id,delta){const ids=profile.decks[key]||[];if(delta<0){const i=ids.indexOf(id);if(i>=0)ids.splice(i,1)}else{const c=poolFor(key).find(x=>x.id===id),limit=c?.cardClass==='Trademark'?1:3;if(countInDeck(ids,id)<limit)ids.push(id)}profile.decks[key]=ids;window._drawDeck()}
function saveDeck(key){if((profile.decks[key]||[]).length<25)return;saveProfile();state=null;home()}
function resetDeck(key){profile.decks[key]=defaultDeckIds(key);saveProfile();deckBuilder(key)}
