'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(root+'/index.html','utf8');
const app=fs.readFileSync(root+'/app.js','utf8');
const version=JSON.parse(fs.readFileSync(root+'/version.json','utf8'));
assert.ok(/^v0\.9\.\d+$/.test(version.version));
const cacheVersion=version.version.replace(/^v/,'');
assert.ok(html.includes(`wa-original-runtime.js?v=${cacheVersion}`),'runtime must load before app');
assert.ok(html.indexOf('wa-original-runtime.js')<html.indexOf(`app.js?v=${cacheVersion}`),'runtime must precede app');
assert.ok(!app.includes("/^LayingTheSmackDown2E\\.gac$/i.test"),'script-backed Laying The Smack Down fallback must be removed');
assert.ok(!app.includes("/^(?:FloatoverDDT|FloatoverDDT2E|TheRocksDDT2E)\\.gac$/i.test"),'mixed DDT fallback must be removed');
assert.ok(app.includes("/^TheRocksDDT2E\\.gac$/i.test"),'scriptless DDT compatibility fallback must remain');
const manifest=JSON.parse(fs.readFileSync(root+'/data/original-runtime-manifest.json','utf8'));
vm.runInThisContext(fs.readFileSync(root+'/wa-original-runtime.js','utf8'));
const runtime=new globalThis.WAOriginalRuntime(manifest);
const state={round:1,control:'player',ended:false,player:{hp:40,maxHp:40,hand:[1],deck:[1,2],discard:[],inPlay:[],location:'InTheRing',onMat:false,stunned:0,inHold:false,pinned:false,warnings:0,momentum:{Knowledge:1}},cpu:{hp:40,maxHp:40,hand:[],deck:[],discard:[],inPlay:[],location:'InTheRing',onMat:false,stunned:0,inHold:false,pinned:false,warnings:0,momentum:{}}};
const page={sourceFile:'ArmDragTakedown.gac',name:'Arm Drag Takedown'};
const result=runtime.run({state,page,event:'Move_Connected',execute:()=>{state.player.hand.push(2);state.player.deck.pop();}});
assert.ok(result.record.changedDomains.includes('zones'));
console.log(JSON.stringify({pass:true,version:version.version,changedDomains:result.record.changedDomains}));
